### ISSUE TITLE
Ignores one of the times

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [danielfernau/unifi-protect-video-downloader#34]
passing in  --start="2020-08-29 18:24:55-0400" --end="2020-08-29 18:26:55-0400" and instead I get video from 2020-08-29 18:24:55-0400 to 2020-08-29 19:00:00-0400

but it seems to randomly (I cannot figure out the pattern...) where it will peg the start time to the hour vs the time I passed in.

so instead of getting 5 min or 8 min I get these hour-long clips

**Comment by danielfernau** [comment]
Hi @ntableman!

Thanks for reporting this issue. Since this tool is primarily designed for downloading larger time spans at a time (i.e. multiple hours, days or even weeks) to be able to archive them outside the Protect system, we have not (yet) focused on implementing it in a way that reliably allows downloading files which are only a few minutes long. 
You might want to use the Protect web interface or mobile app for this instead. There you can select the desired start and end time before downloading the video clip. 

I'll keep the issue open for now but we'll probably not resolve it in the near future. However, feel free to add more details in the comments if you like, as it might be helpful for us once we start working on it.

**Comment by ntableman** [comment]
Yeah, the issue here is I want 1 min of the action so I do not have to pour over days of video. Seems like a pretty normal use case to me, but I get your point as to where your focus is. It is really random. I always ask for 60 seconds, sometimes I get 5 min, sometimes an hour, sometimes 5 hours. I've this connected up to some ML work that picks out cars and people send an mqtt message about the time interval and such then runs your script. I am using the v2 by the way. The reasoning here is that I don't care about the 99% of the time that NOTHING HAPPENS :) and I do not click when I can code :) then I have the videos uploaded to a solid video server vs protect which kind of is the pits when wanting to watch events.

I guess I can also take a look at your code and figure out why it is not paying attention to end times.

**Comment by ntableman** [comment]
HAHA, this explains it.

 help=(
        "Download range end time. "
        # TODO(danielfernau): uncomment the next line as soon as the feature is implemented
        # "If omitted, the time of the last available recording for each camera will be used."
    )

**Comment by ntableman** [comment]
I thought it was a bug, turns out you are doing it on purpose line 218 of main, seems like if you just make a flag that uses that section or just ignores it, this is an easy change. I am testing it out now.

**Comment by ntableman** [comment]
wow you have a lot of fun in there to do that hour to hour thing - I yanked it all out and it is working!

**Comment by danielfernau** [comment]
Ah, yes. For my use-case it originally was important to have the files aligned to full-hour-segments, so I wrote that alignment thing for when the start/end from the command line is not exactly a full hour. In version 2.x.x+ there'll be probably an additional command line parameter to enable/disable the alignment part. Thanks for the update!

**Comment by nittanygeek** [comment]
> wow you have a lot of fun in there to do that hour to hour thing - I yanked it all out and it is working!

How does one do this?  I need this for extracting specific times as well, and it's trying to pull 45 minute long videos for what should be much shorter.

**Comment by danielfernau** [comment]
@nittanygeek
The code in question can be found here: https://github.com/unifi-toolbox/unifi-protect-video-downloader/blob/master/protect_archiver/utils.py#L44-L72

I'll add a few command line options with the next release to disable the 1-hour-alignment as well as to allow downloading shorter files. At the time of writing the tool I needed each file to be aligned with the full hour, that's why this code exists in the first place.

Hope this helps until I have a bit of free time to work on the next release.

**Comment by nittanygeek** [comment]
Perfect, thanks for pointing me in the right direction!  I just slapped a "yield start,end" in place of the previous code, rebuilt the container and it's working perfectly!  Thanks much!

**Comment by SebDominguez** [comment]
I'm also looking forward on this issue as I'm interested in downloading only 30 secondes of footage when I have sensors reporting an events here using homeassistant
